<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYl4NlGI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYl4NlGI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYl4NlGI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYl4NlGI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYl4NlGI\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yl4NlGI',
    'container.build_id' => 'f8ea2531',
    'container.build_time' => 1728379099,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYl4NlGI');
